"""AI agent that answers weather questions using a custom tool."""

import os  # for interacting with the operating system, such as reading environment variables

from dotenv import load_dotenv  # for loading environment variables from a .env file
from langchain.agents import create_agent  # for creating an AI agent
# for defining tools that the agent can use
from langchain_core.tools import tool
# for interacting with OpenAI's chat models
from langchain_openai import ChatOpenAI

# for retrieving weather data for a city using Open-Meteo
from weather_tool import get_weather


# Load environment variables from a .env file, allowing the program to access sensitive information like API keys without hardcoding them into the source code.
load_dotenv()


@tool  # Decorator that registers the function as a tool for the AI agent.
def get_weather_for_city(city: str) -> dict:
    """Get the current weather for a city.

    Use this tool when the user asks about current weather,
    temperature, humidity, precipitation, or wind in a city.
    """

    return get_weather(city)


model = ChatOpenAI(
    model=os.getenv("OPENAI_MODEL", "gpt-5.6-luna"),
    # Set to 0 for deterministic responses, meaning the model will produce the same output for the same input.
    temperature=0,
    # Limit the response length to 512 tokens to control the amount of text generated by the model.
    max_tokens=512,
    # Retrieve the OpenAI API key from environment variables for authentication with the OpenAI API.
    api_key=os.getenv("OPENAI_API_KEY"),

    # Use the Responses API for generating responses, which may offer improved performance or features compared to other APIs.
    use_responses_api=True,
)


weather_agent = create_agent(
    model=model,
    tools=[get_weather_for_city],
    system_prompt=(
        "You are a helpful weather assistant. "
        "Use get_weather_for_city for current weather questions. "
        "Extract the city from the user's request. "
        "Never invent weather information. "
        "If the user does not provide a city, ask for one."
        "If the user requests a future forecast, explain that this version "
        "Only supports current weather and offer to provide current conditions."
    ),
)


if __name__ == "__main__":
    user_prompt = input("Ask the weather agent: ")

    result = weather_agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": user_prompt,
                }
            ]
        }
    )

    # Get the last message from the agent's response, which is typically the final answer to the user's query.
    final_message = result["messages"][-1]

    print("\nWeather Agent:")
    print(final_message.text)
