"""AI agent that answers weather questions using a custom tool."""

import os  # for interacting with the operating system, such as reading environment variables

from dotenv import load_dotenv  # for loading environment variables from a .env file
from langchain.agents import create_agent  # for creating an AI agent
# for defining tools that the agent can use
from langchain_core.tools import tool
# for interacting with OpenAI's chat models
from langchain_openai import ChatOpenAI

# for retrieving weather data for a city using Open-Meteo
from weather_tool import get_weather


# Load environment variables from a .env file, allowing the program to access sensitive information like API keys without hardcoding them into the source code.
load_dotenv()


@tool
def get_weather_for_city(city: str) -> dict:
    """Get the current weather for a city.

    Use this tool when the user asks about current weather,
    temperature, humidity, precipitation, or wind in a city.
    """

    try:
        weather = get_weather(city)

        return {
            "status": "success",
            "data": weather,
        }

    except ValueError as error:
        return {
            "status": "error",
            "error_type": "location_not_found",
            "message": str(error),
        }


model = ChatOpenAI(
    model=os.getenv("OPENAI_MODEL", "gpt-5.6-luna"),
    # Set to 0 for deterministic responses, meaning the model will produce the same output for the same input.
    temperature=0,
    # Limit the response length to 512 tokens to control the amount of text generated by the model.
    max_tokens=512,
    # Retrieve the OpenAI API key from environment variables for authentication with the OpenAI API.
    api_key=os.getenv("OPENAI_API_KEY"),

    # Use the Responses API for generating responses, which may offer improved performance or features compared to other APIs.
    use_responses_api=True,
)


weather_agent = create_agent(
    model=model,
    tools=[get_weather_for_city],
    system_prompt=(
        "You are a narrowly scoped current-weather assistant. "

        "SUPPORTED CAPABILITY: "
        "You only provide current temperature, current weather condition, "
        "feels-like temperature, humidity, precipitation, and wind for a "
        "specific city. "

        "SUPPORTED REQUEST RULES: "
        "When the user asks for supported current weather for a specific "
        "city, call get_weather_for_city exactly once. "
        "Extract only the city requested by the user. "
        "Base the final answer only on information returned by the tool. "

        "MISSING OR BROAD LOCATION: "
        "If the location is missing or is broader than a city, such as a "
        "country, ask the user to provide a specific city. "
        "Do not call the tool until a specific city is provided. "

        "FUTURE OR HISTORICAL REQUESTS: "
        "Do not call the tool for future or historical weather. "
        "Explain that this version only supports current weather. "
        "You may offer to provide current conditions for a specific city. "
        "Do not provide seasonal climate information, predictions, "
        "estimates, recommendations, or general-knowledge weather advice. "

        "TRAVEL RECOMMENDATIONS: "
        "Do not recommend whether, when, or where the user should travel "
        "or celebrate an event. "
        "Do not discuss prices, crowds, seasons, beaches, islands, "
        "activities, ocean conditions, or typical future weather. "
        "State that current weather cannot support a future travel "
        "recommendation, and optionally offer current city weather. "

        "OTHER UNSUPPORTED REQUESTS: "
        "For arithmetic, flight status, flight cancellations, tides, "
        "marine conditions, astronomy, meteor showers, or any request "
        "outside current city weather, do not answer the underlying "
        "question using general knowledge. "
        "Do not call the weather tool. "
        "Briefly explain that this assistant only provides current weather "
        "for a specific city. "

        "ERROR HANDLING: "
        "If the weather tool returns status='error', explain the error "
        "clearly and ask the user for a valid city when appropriate. "

        "STRICT GROUNDING: "
        "Never invent, estimate, predict, or supplement information not "
        "returned by the weather tool. "
        "A correct limitation followed by unsupported advice is still a "
        "violation. "
        "After refusing an unsupported request, stop after the limitation "
        "and optional offer of current city weather. "
    ),
)


if __name__ == "__main__":
    user_prompt = input("Ask the weather agent: ")

    result = weather_agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": user_prompt,
                }
            ]
        }
    )

    # Get the last message from the agent's response, which is typically the final answer to the user's query.
    final_message = result["messages"][-1]

    print("\nWeather Agent:")
    print(final_message.text)
